#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu machine

# Update the system
apt update

# Install Nginx
apt install -y nginx

# Configure Nginx
tee /etc/nginx/sites-available/default >/dev/null <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        echo 'Hello World!';
    }
}
EOF

# Restart Nginx
service nginx restart
