#!/usr/bin/env/ bash
# running apache2 on the 265-0 docker-container
echo "ServerName localhost">>/etc/apache2.conf
docker run -p 8080:80 -d -it holbertonschool/265-0
docker exec -it <container_id> /bin/bash -c "service apache2 start"
docker exec -it <container_id> /bin/bash -c "service apache2 reload"

